# Model configuration
model:
  type: lstm
  embedding_dim: 256
  hidden_dim: 256
  num_layers: 2
  bidirectional: true
  dropout: 0.2
  output_dim: 3  # number of classes

# Training configuration
training:
  epochs: 10
  batch_size: 64
  optimizer:
    type: adam
    learning_rate: 0.001
  criterion:
    type: cross_entropy
  device: gpu  # or 'cpu' if no GPUs available
  log_dir: logs/  # directory to save tensorboard logs
  checkpoint_dir: checkpoints/  # directory to save model checkpoints
  train_csv: /home/anagha/saarthi/task_data/train_data.csv  # path to training data
  valid_csv: /home/anagha/saarthi/task_data/valid_data.csv # path to validation data

# Testing configuration
testing:
  batch_size: 1
  device: cpu
  test_csv: /home/anagha/saarthi/task_data/valid_data.csv  # path to testing data
